SFAccountingSystem/SFAccountingSystem/Controllers/ExpensesController.cs
using Microsoft.AspNetCore.Mvc;

namespace SFAccountingSystem.Controllers
{
    public class ExpensesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SFAccountingSystem/SFAccountingSystem/Controllers/InvoicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SFAccountingSystem.Core.Models;
using SFAccountingSystem.Core.Services;

namespace SFAccountingSystem.Controllers
{
    public class InvoicesController : Controller
    {
        private readonly InvoicesService _invoiceService;
        private readonly UserService _userService;

        public InvoicesController(InvoicesService invoiceService,
                                  UserService userService)
        {
            _invoiceService = invoiceService;
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Users = new SelectList(await _userService.List(), "Id", "Name");

            return View(await _invoiceService.List());
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser(Invoice model)
        {
            await _invoiceService.UpdateUser(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateNrNumber(Invoice model)
        {
            await _invoiceService.UpdateNrNumber(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateValue(Invoice model)
        {
            await _invoiceService.UpdateValue(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateDate(Invoice model)
        {
            await _invoiceService.UpdateDate(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Approve(int id)
        {
            await _invoiceService.Approve(id);
            return RedirectToAction("Index");
        }
    }
}

SFAccountingSystem/SFAccountingSystem/Controllers/RecordOFXController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SFAccountingSystem.Core.Enums;
using SFAccountingSystem.Core.Models;
using SFAccountingSystem.Core.Services;
using SFAccountingSystem.Core.ViewModels;
using System.Globalization;

namespace SFAccountingSystem.Controllers
{
    public class RecordOFXController : Controller
    {
        private readonly RecordOFXService _recordOFXService;
        private readonly UserService _userService;

        public RecordOFXController(RecordOFXService recordOFXService,
                                    UserService userService)
        {
            _recordOFXService = recordOFXService;
            _userService = userService;
        }

        public async Task<IActionResult> Index(int? Month = null, int? Year = null, RecordOFXBank? Bank = null)
        {
            ViewBag.Banks = new SelectList(Enum.GetValues(typeof(RecordOFXBank))
                                                .Cast<RecordOFXBank>()
                                                .Select(x => new
                                                {
                                                    DisplayName = x.ToName<RecordOFXBank>(),
                                                    Id = (int)x
                                                }), "Id", "DisplayName");

            ViewBag.Groups = new SelectList(Enum.GetValues(typeof(RecordOFXGroup))
                                                .Cast<RecordOFXGroup>()
                                                .Select(x => new
                                                {
                                                    DisplayName = x.ToName<RecordOFXGroup>(),
                                                    Id = (int)x
                                                }), "Id", "DisplayName");


            ViewBag.Months = new SelectList((new CultureInfo("en-US")).DateTimeFormat.MonthNames
                                        .Where(x => !string.IsNullOrEmpty(x))
                                        .Select((x, i) => new
                                        {
                                            DisplayName = x,
                                            Id = i + 1
                                        }), "Id", "DisplayName");

            ViewBag.Users = new SelectList(await _userService.List(), "Id", "Name");

            var filter = new RecordOFXFilter
            {
                Month = Month,
                Year = Year,
                Bank = Bank
            };
            ViewBag.Filter = filter;

            return View(await _recordOFXService.List(filter));
        }

        [HttpPost]
        public async Task<IActionResult> Index(ObjectFileViewModel model)
        {
            await _recordOFXService.Add(model.Ofx, model.Bank);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Approve(int id)
        {
            await _recordOFXService.Approve(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateGroup(RecordOFX model)
        {
            await _recordOFXService.UpdateGroup(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateUser(RecordOFX model)
        {
            await _recordOFXService.UpdateUser(model);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> UpdateSubGroup(RecordOFX model)
        {
            await _recordOFXService.UpdateSubGroup(model);
            return RedirectToAction("Index");
        }
    }
}

SFAccountingSystem/SFAccountingSystem/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SFAccountingSystem.Core;
using SFAccountingSystem.Core.Enums;
using SFAccountingSystem.Core.Models;

namespace SFAccountingSystem.Controllers
{
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;

        public readonly DataContext _dataContext;

        public UserController(ILogger<UserController> logger, DataContext dataContext)
        {
            _logger = logger;
            _dataContext = dataContext;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _dataContext.Users.ToListAsync();
            return View(users);
        }

        public IActionResult Create()
        {
            SelectList select1 = new(Enum.GetValues(typeof(UserEntity))
                                                .Cast<UserEntity>()
                                                .Select(x => new
                                                {
                                                    DisplayName = x.ToName<UserEntity>(),
                                                    Id = (int)x
                                                }), "Id", "DisplayName");

            SelectList select2 = new(Enum.GetValues(typeof(UserType))
                                                .Cast<UserType>()
                                                .Select(x => new
                                                {
                                                    DisplayName = x.ToName<UserType>(),
                                                    Id = (int)x
                                                }), "Id", "DisplayName");

            ViewBag.Select1 = select1;
            ViewBag.Select2 = select2;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(User user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }

            await _dataContext.Users.AddAsync(user);
            await _dataContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int Id)
        {
            SelectList select1 = new(Enum.GetValues(typeof(UserEntity))
                                                .Cast<UserEntity>()
                                                .Select(x => new
                                                {
                                                    DisplayName = x.ToName<UserEntity>(),
                                                    Id = (int)x
                                                }), "Id", "DisplayName");

            SelectList select2 = new(Enum.GetValues(typeof(UserType))
                                                .Cast<UserType>()
                                                .Select(x => new
                                                {
                                                    DisplayName = x.ToName<UserType>(),
                                                    Id = (int)x
                                                }), "Id", "DisplayName");

            ViewBag.Select1 = select1;
            ViewBag.Select2 = select2;

            var user = await _dataContext.Users.FirstOrDefaultAsync(x => x.Id == Id);

            if (user == null)
            {
                throw new Exception("There is not a user with this Id");
            }

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Update(User user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            else if (ModelState.IsValid)
            {
                var current = await _dataContext.Users.FirstOrDefaultAsync(x => x.Id == user.Id);

                if (current != null)
                {
                    current.Name = user.Name;
                    current.CpfCnpj = user.CpfCnpj;
                    current.Type = user.Type;
                    current.Entity = user.Entity;

                    _dataContext.Users.Update(current);
                    await _dataContext.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
            }

            throw new NotImplementedException();
        }

        public async Task<IActionResult> Delete(int Id)
        {
            var user = await _dataContext.Users.FirstOrDefaultAsync(x => x.Id == Id);

            if (user == null)
            {
                throw new Exception("There is not a user with this Id");
            }

            else if (user != null)
            {
                _dataContext.Users.Remove(user);
                await _dataContext.SaveChangesAsync();
            }

            return RedirectToAction("Index");
        }
    }
}

SFAccountingSystem/SFAccountingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Html.Raw(ViewData["Title"]) - SFAccountingSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SFAccountingSystem.styles.css" asp-append-version="true" />

    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SFAccountingSystem</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecordOFXSubGroup" asp-action="Index">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RecordOFX" asp-action="Index">Bank Statements</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Intermediations" asp-action="Index">Intermediations</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoices" asp-action="Index">Invoices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BalanceSheet" asp-action="Index">Balance Sheet</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()

            @if (!ViewData.ModelState.IsValid) @*msg se houver erro de criacao ou edicao*@
            {
                    <div class="notice d-flex bg-light-danger rounded border-primary border border-danger border-dashed mb-2 p-6">
                        <div class="d-flex flex-stack flex-grow-1">
                            <div class="fw-bold">
                                <div asp-validation-summary="All" class="fs-6 text-gray-600"></div>
                            </div>
                        </div>
                    </div>
            }

            @*modal usado para delete*@
            <div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel" aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Delete</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>
                  <div class="modal-body">
                    Do you really want to DELETE this entry?
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a id="confirmDeleteBtn" class="btn btn-danger">Delete</a>
                  </div>
                </div>
              </div>
            </div>

            @*java que chama o modal*@
            <script>
              document.addEventListener('DOMContentLoaded', function() {
                var deleteConfirmationModal = document.getElementById('deleteConfirmationModal');
                var confirmDeleteBtn = document.getElementById('confirmDeleteBtn');

                deleteConfirmationModal.addEventListener('show.bs.modal', function(event) {
                  var button = event.relatedTarget;
                  var deleteUrl = button.getAttribute('data-delete-url');
                  confirmDeleteBtn.setAttribute('href', deleteUrl);
                });
              });
            </script>

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SFAccountingSystem - Powered by <a href="http://www.semprefichas.com.br">Sempre Fichas</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>