SFAccountingSystem/SFAccountingSystem/Controllers/IntermediationsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SFAccountingSystem.Core.Models;
using SFAccountingSystem.Core.Services;

namespace SFAccountingSystem.Controllers
{
    public class IntermediationsController : Controller
    {
        private readonly UserService _userService;
        private readonly IntermediationsService _intermediationsService;

        public IntermediationsController(UserService userService,
                                         IntermediationsService intermediationsService)
        {
            _userService = userService;
            _intermediationsService = intermediationsService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _intermediationsService.List());
        }

        public async Task<IActionResult> New()
        {
            ViewBag.Users = new SelectList(await _userService.List(), "Id", "Name");
            ViewBag.RecordOfxs = await _intermediationsService.GetNotBounded();

            return View(new Intermediation());
        }

        [HttpPost]
        public async Task<IActionResult> New(Intermediation model)
        {
            await _intermediationsService.Add(model);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> View(int id)
        {
            ViewBag.Users = new SelectList(await _userService.List(), "Id", "Name");
            return View(await _intermediationsService.Get(id));
        }

        [HttpPost]
        public async Task<IActionResult> View(int id, Intermediation model)
        {
            await _intermediationsService.CreateInvoice(model);
            return RedirectToAction("Index", "Invoices");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _intermediationsService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

SFAccountingSystem/SFAccountingSystem/Views/Intermediations/Index.cshtml
@model List<Intermediation>

<div class="row">
    <a class="btn btn-success" asp-area="" asp-controller="Intermediations" asp-action="New">New</a>
</div>
<div class="row">
    <div class="col-12">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Data
                    </th>
                    <th>
                        Registers count
                    </th>
                    <th>
                        Actions
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.CreatedAt.ToString("dd/MM/yyyy HH:mm")
                        </td>
                        <td>
                            @item.RecordsOFXes.Count()
                        </td>
                        <td>
                            <a class="btn btn-sm btn-info" href="/intermediations/view/@item.Id">create invoice</a>
                            <a class="btn btn-sm btn-danger" href="/intermediations/delete/@item.Id">delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

SFAccountingSystem/SFAccountingSystem/Views/Intermediations/New.cshtml
@model Intermediation

@{
    ViewData["Title"] = "Register a intermediation";
}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="mb-4 text-center">@ViewData["Title"]</h1>
            <form method="post">
                <input type="hidden" asp-for="Id" />

                <div class="mb-3">
                    <label class="form-label" for="Group">Client</label>
                    <select class="form-control" id="UserId" asp-for="UserId" asp-items="ViewBag.Users" required>
                        <option></option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="Description">Intermediations</label>
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>
                                    Data
                                </th>
                                <th>
                                    User
                                </th>
                                <th>
                                    Value
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in (List<RecordOFX>)ViewBag.RecordOfxs)
                            {
                                <tr>
                                    <td>
                                        <input type="checkbox" name="RecordOfxIds" checked value="@item.Id" />
                                    </td>
                                    <td>
                                        @item.Date.ToString("dd/MM/yyyy")
                                    </td>
                                    <td>
                                        @if (item.User != null)
                                        {
                                            <span>
                                                @item.User.Name
                                            </span>
                                        }
                                    </td>
                                    <td>
                                        @item.Value.ToString("c")
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <div class="mb-3">
                    <input class="btn btn-success w-100" type="submit" value="Save" />
                </div>
            </form>
        </div>
    </div>
</div>

SFAccountingSystem/SFAccountingSystem/Views/Intermediations/View.cshtml
@model Intermediation

@{
    ViewData["Title"] = "View a intermediation";
}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="mb-4 text-center">@ViewData["Title"]</h1>
            <form method="post">
                <input type="hidden" asp-for="Id" />
                <input type="hidden" asp-for="UserId" />

                <div class="mb-3">
                    <label class="form-label" for="Group">Client</label>
                    <select class="form-control" id="UserId" asp-for="UserId" asp-items="ViewBag.Users" required disabled>
                        <option></option>
                    </select>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="Description">Intermediations</label>
                    @foreach (var item in Model.RecordsOFXes.GroupBy(x => x.UserId))
                    {
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        Data
                                    </th>
                                    <th>
                                        User
                                    </th>
                                    <th>
                                        Value
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var e in item.ToList())
                                {
                                    <tr>
                                        <td>
                                            @e.Date.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>
                                            @if (e.User != null)
                                            {
                                                <span>
                                                    @e.User.Name
                                                </span>
                                            }
                                        </td>
                                        <td>
                                            @e.Value.ToString("c")
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                        <h5>
                            <input type="checkbox" name="UserIds" value="@item.First().UserId" checked />
                            @item.First().User.Name: @item.ToList().Sum(x => x.Value > 0 ? x.Value : decimal.Negate(x.Value)).ToString("c")
                        </h5>

                        <hr />
                    }

                    <h3>Total value: @Model.RecordsOFXes.Sum(x => x.Value > 0 ? x.Value : decimal.Negate(x.Value)).ToString("c")</h3>
                </div>
                <div class="mb-3">
                    <label class="form-label">Intermediation value</label>
                    <input class="form-control" asp-for="Value" required />
                </div>
                <div class="mb-3">
                    <input class="btn btn-success w-100" type="submit" value="Save" />
                </div>
            </form>
        </div>
    </div>
</div>